import React, { useState } from 'react';
import { Room } from '../types';
import { Button } from './ui/Button';

interface RoomEditorModalProps {
  room?: Room | null; // Optional: if undefined/null, it's CREATE mode
  onClose: () => void;
  onSave: (roomData: Room) => void;
  onDelete?: (roomId: string) => void;
  isLoading: boolean;
}

export const RoomEditorModal: React.FC<RoomEditorModalProps> = ({ room, onClose, onSave, onDelete, isLoading }) => {
  const isEditing = !!room;
  
  const [name, setName] = useState(room?.name || '');
  const [imageUrl, setImageUrl] = useState(room?.imageUrl || 'https://picsum.photos/400/300');
  const [capacity, setCapacity] = useState(room?.capacity || 20);
  const [featuresStr, setFeaturesStr] = useState(room?.features.join(', ') || 'Proyector, Sillas, WiFi');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const features = featuresStr.split(',').map(f => f.trim()).filter(f => f.length > 0);
    
    onSave({
      id: room?.id || '', // ID will be ignored or generated by storage on create
      name,
      imageUrl,
      capacity,
      features
    });
  };

  const handleDelete = () => {
    if (onDelete && room?.id) {
      if (window.confirm('¿Estás seguro de que quieres eliminar este salón? Esta acción no se puede deshacer.')) {
        onDelete(room.id);
      }
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
      <div className="bg-white w-full max-w-md rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        <div className="bg-gray-800 p-4 text-white flex justify-between items-center shrink-0">
          <h3 className="font-bold text-lg">{isEditing ? 'Editar Salón' : 'Crear Nuevo Salón'}</h3>
          <button onClick={onClose} className="text-white/80 hover:text-white">
            <i className="fas fa-times"></i>
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-4 overflow-y-auto">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Nombre del Salón</label>
            <input 
              type="text" 
              required
              placeholder="Ej: Salón San José"
              className="w-full p-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Capacidad (Personas)</label>
            <input 
              type="number" 
              required
              min="1"
              className="w-full p-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
              value={capacity}
              onChange={(e) => setCapacity(Number(e.target.value))}
            />
          </div>

          <div>
             <label className="block text-sm font-medium text-gray-700 mb-1">Características (separadas por coma)</label>
             <input 
              type="text"
              placeholder="Ej: Aire acondicionado, Proyector"
              className="w-full p-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
              value={featuresStr}
              onChange={(e) => setFeaturesStr(e.target.value)}
             />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">URL de la Imagen</label>
            <input 
              type="url" 
              required
              className="w-full p-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
              value={imageUrl}
              onChange={(e) => setImageUrl(e.target.value)}
            />
            <p className="text-xs text-gray-500 mt-1">Vista previa:</p>
            <div className="mt-1 h-32 w-full bg-gray-100 rounded-lg overflow-hidden border border-gray-200">
               <img src={imageUrl} alt="Preview" className="w-full h-full object-cover" onError={(e) => (e.currentTarget.src = 'https://via.placeholder.com/400x300?text=Error+URL')} />
            </div>
          </div>

          <div className="pt-2 flex flex-col gap-3">
            <Button type="submit" variant="primary" fullWidth isLoading={isLoading}>
              {isEditing ? 'Guardar Cambios' : 'Crear Salón'}
            </Button>
            
            <div className="flex gap-3">
               <Button type="button" variant="secondary" onClick={onClose} fullWidth className="flex-1">
                 Cancelar
               </Button>
               {isEditing && (
                 <Button type="button" variant="danger" onClick={handleDelete} className="px-4" title="Eliminar Salón">
                   <i className="fas fa-trash-alt"></i>
                 </Button>
               )}
            </div>
          </div>
        </form>
      </div>
    </div>
  );
};